#!/bin/bash

############################################ BEGIN EDITS ###################################

# Set this to the path to your google drive folder that you are tracking
# CASE IS IMPORTANT. If your directory has a capital letter in the name, reflect it here
GOOGLE_DIR=Writing

# SET this to the path for where you are dropping your sync's in Storyist.
SE=$HOME/Path/to/files/from/Storyist

# Set a tmp directory for us to unpack to - this will be deleted on exit
# DO NOT SET THIS TO /tmp - we aren't smart enough not to delete everything
TMPDIR=/tmp/storyist
############################################ END EDITS #####################################
# You may of course modify after this point - but at your own peril...

# We create the symlink between Google Drive (with spaces) to just Google - saves pain later
if [ ! -L "$HOME/Google" ]; then
	ln -s $HOME/Google\ Drive $HOME/Google
fi

GOOGLE=$HOME/Google/$GOOGLE_DIR
ARCHIVE=${SE}/GoogleTransfer

export IFS='
'

if [ -d ${TMPDIR} ]; then
	/bin/rm ${TMPDIR}/*.xml > /dev/null 2>&1
else
	mkdir -p ${TMPDIR}
fi

if [ ! -d ${ARCHIVE} ]; then
	mkdir -p ${ARCHIVE}
fi

touch -t `date +%m%d0000` /tmp/$$
for x in `find ${SE} -name "*.story" -type f -newer /tmp/$$ |grep -v GoogleTransfer`; do
  file=`echo $x| sed -e "s|${SE}||g" -e "s|/||g"` 
	newf=`echo $file| sed -e "s/\.story//" -e "s| |_|g"`
	unzip -c ${SE}/${file} story.xml | sed 's|</b>|-|g' | sed 's|<[^>]*>||g'|sed -e "s/  /:/g"  |egrep -v ":{1,}$"|sed -e "s/:/ /g" > ${TMPDIR}/${newf}-story.txt
	if [ -f ${ARCHIVE}/${newf}-story.txt ]; then
		OLDCOUNT=`wc -w ${ARCHIVE}/${newf}-story.txt|sed -e "s|/.*||" -e "s/ //g"`
	fi
	NEWCOUNT=`wc -w ${TMPDIR}/${newf}-story.txt|sed -e "s|/.*||" -e "s/ //g"`
	if [ ${NEWCOUNT} -gt ${OLDCOUNT} ]; then
		COUNT=$(expr $NEWCOUNT - $OLDCOUNT)
	else
		COUNT=${NEWCOUNT}
	fi
	echo $COUNT > ${GOOGLE}/${newf}-count.txt
	mv ${TMPDIR}/${newf}-story.txt ${ARCHIVE}/${newf}-story.txt
done 
rm /tmp/$$

/bin/rm ${TMPDIR}/*.txt > /dev/null 2>&1
